### PR TITLE
Consider updated binding format allowing multiple application-specific backends

### PR DESCRIPTION
**Pull request by vzhabko**
I was not able to test localconfig, so I may need help with that.

### CODE REVIEW

**Review by mp911de — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution. The pull request contains a lot of changes to license headers and formatting changes. [Here's the IDE formatter config](https://github.com/spring-projects/spring-vault/tree/master/etc/ide) for your convenience. 

Please remove the formatting changes to continue.

**Comment by vzhabko** [comment]
I have removed as much as I could of extra formatting as you requested. Formatter, that you provided, does not restore formatting to the original. So I did it manually.

**Comment by mp911de** [comment]
Great job, thanks a lot. I'll take this pull request from here.

**Review by mp911de — APPROVED** [review]

**Comment by mp911de** [comment]
We need to consider the old format as well, so I'm going to restore compatibility that considers both forms (single and multiple backends).

**Comment by mp911de** [comment]
That's merged now.

**Pull request closed without merging**
